#!/usr/bin/env bash
# Create the Cognito User Pool + public app client and write the
# frontend's public auth-config.js. Idempotent via deploy/beta.env.
source "$(dirname "${BASH_SOURCE[0]}")/00-config.sh"

if [ -z "${COGNITO_POOL_ID:-}" ]; then
  echo "Creating Cognito user pool…"
  POOL_ID=$(aws_ cognito-idp create-user-pool \
    --pool-name "${PROJECT}-users" \
    --auto-verified-attributes email \
    --username-attributes email \
    --admin-create-user-config 'AllowAdminCreateUserOnly=true' \
    --policies 'PasswordPolicy={MinimumLength=8,RequireUppercase=false,RequireLowercase=false,RequireNumbers=false,RequireSymbols=false}' \
    --query 'UserPool.Id' --output text)
  save_state COGNITO_POOL_ID "$POOL_ID"
fi
echo "User pool: $COGNITO_POOL_ID"

if [ -z "${COGNITO_CLIENT_ID:-}" ]; then
  echo "Creating app client…"
  CLIENT_ID=$(aws_ cognito-idp create-user-pool-client \
    --user-pool-id "$COGNITO_POOL_ID" \
    --client-name "${PROJECT}-web" \
    --no-generate-secret \
    --explicit-auth-flows ALLOW_USER_PASSWORD_AUTH ALLOW_REFRESH_TOKEN_AUTH \
    --query 'UserPoolClient.ClientId' --output text)
  save_state COGNITO_CLIENT_ID "$CLIENT_ID"
fi
echo "App client: $COGNITO_CLIENT_ID"

# ---- Mandatory TOTP MFA (software token) ----
echo "Enforcing TOTP MFA (MfaConfiguration=ON)…"
aws_ cognito-idp set-user-pool-mfa-config \
  --user-pool-id "$COGNITO_POOL_ID" \
  --mfa-configuration ON \
  --software-token-mfa-configuration Enabled=true >/dev/null

cat > "${SITE_DIR}/assets/auth-config.js" <<EOF
/* Public Cognito configuration — generated by deploy/provision-cognito.sh.
   (userPoolId / clientId are public identifiers, not secrets.) */
window.STONEWELL_AUTH = {
  region: "${AWS_REGION}",
  userPoolId: "${COGNITO_POOL_ID}",
  clientId: "${COGNITO_CLIENT_ID}"
};
EOF
echo "Wrote ${SITE_DIR}/assets/auth-config.js"
